//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.08 at 12:57:18 AM IDT 
//


package yar.quadraturin.config;

public class StageConfig {
   protected String initialScene = "q-intro";
    
    private SceneConfig [] scenes;

 
    public SceneConfig [] getScenes() { return scenes; }

    public String getInitialScene() 
    {
    	return initialScene;
    }
}
