//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.08 at 12:57:18 AM IDT 
//


package yarangi.graphics.quadraturin.config;

public class EkranConfig {

    protected int xres;
    protected int yres;
    protected boolean antialiasing;
   protected int maxFPS;
    
 
    /**
     * Gets the value of the xres property.
     * 
     */
    public int getXres() {
        return xres;
    }

    /**
     * Sets the value of the xres property.
     * 
     */
    public void setXres(int value) {
        this.xres = value;
    }

    /**
     * Gets the value of the yres property.
     * 
     */
    public int getYres() {
        return yres;
    }

    /**
     * Sets the value of the yres property.
     * 
     */
    public void setYres(int value) {
        this.yres = value;
    }

    /**
     * Gets the value of the antialiasing property.
     * 
     */
    public boolean isAntialiasing() {
        return antialiasing;
    }

    /**
     * Sets the value of the antialiasing property.
     * 
     */
    public void setAntialiasing(boolean value) {
        this.antialiasing = value;
    }

    /**
     * Gets the value of the maxFps property.
     * 
     */
    public int getMaxFps() {
        return maxFPS;
    }

    /**
     * Sets the value of the maxFps property.
     * 
     */
    public void setMaxFps(int value) {
        this.maxFPS = value;
    }
 
}
